### ISSUE TITLE
4.faza

### ISSUE THREAD

**Issue by PikkaR** [PikkaR/APPR-2014-15#3]
Pozdravljeni.
Zdaj sem na novo uvozila tabele za 4.fazo (imenujejo se Analiza2010,...,Analiza2014) in vsebujejo imena dirkališč, državo v kateri se dirkališče nahaja, dolžino dirkalne steze, ter najhitrejši krog (torej hitrost in čas). Potem sem te podatke razdelila v 3 sklope, ki se imenujejo Čas, Hitrost ter Dolžina v katerih sem primerjala podatke za posamezno dirkališče od leta 2010 do 2014. Nato sem za vse te podatke naredila še grafe, na katerih je razvidno kako so se dolžina, hitrost in čas skozi leta spreminjajo. 
Zanima me, kako naj zdaj zaključim to 4.fazo? Ali je dovolj, če bi naredila animacijo in se npr. prikažejo grafi ter se najprej prikažejo podatki za 2010, potem 2011, potem 2012 itd.? Zanima me tudi, ali je kaj narobe, saj sem čas najhitrejše odpeljanega kroga podala v sekundah, saj mi zaradi vseh , in . ni vse delovalo in sem potem vse spremenila v sekunde že kar v tabelah v Excelu? Hvala za pomoč.

**Comment by jaanos** [comment]
Najprej bi opozoril na to, da definiraš spremenljivko `CaS` (z velikim `S`), kasneje se pa nanašaš na `Cas` (z malim `s`), zato se ti program ustavi. Najbolje bo, če popraviš kar pri definiciji.

Trenutno rišeš vse s stolpčnimi grafi, ki morda niso najboljši način predstavitve teh podatkov - v vsakem primeru bi potrebovala še legendo, ki pove, kaj kateri stolpec pove; poleg tega se dolžine seveda večinoma ne spreminjajo. Če hočeš primerjati npr. hitrosti skozi leta, bo res najbolje narediti animacijo (torej v vsaki sličici prikažeš za vsako dirkališče samo en stolpec).

Kar bi lahko še naredila, je to, da bi vse te razpredelnice združila v eno (to narediš s funkcijo `rbind` - prej v vsako razpredelnico dodaj še stolpec z letom), potem pa narisala graf najhitrejših krogov glede na dolžino dirkališča (točkam lahko nastaviš npr. barvo ali obliko glede na dirkališče ali leto). Potem lahko iz teh podatkov zgradiš model in narišeš ustrezno krivuljo na graf.

Ta rešitev s pretvorbo v sekunde je v redu in seveda nujna, če hočeš karkoli pametnega početi s podatki (lahko bi jo sicer naredila v R-ju, a je tudi tako v redu). Opazil sem sicer, da imaš nekje za čas in hitrost ničle - to so manjkajoči podatki, tako da jih raje kar pobriši (pusti prazne celice), da jih bo R spoznal kot `NA`.
